Timeout 2400
ProxyTimeout 2400
ProxyBadHeader Ignore

<Location /dozzle>
  AuthType shibboleth
  ShibRequestSetting requireSession 1
  ShibRequireSession on
  ShibUseHeaders On
  require shib-session
</Location>

RequestHeader unset Authorization
ProxyPass /dozzle/dozzSSO !
ProxyPass /dozzle http://dozzle:8080/dozzle

